// Sovereign Ledger — Recurring Transaction Processor
import dayjs from 'dayjs';

/**
 * Check if a recurring transaction is due and generate new transactions
 * @param {Array} transactions - All existing transactions
 * @param {string} lastCheckDate - ISO string of last check date
 * @returns {Array} New transactions to add
 */
export const processRecurringTransactions = (transactions, lastCheckDate) => {
  const now = dayjs();
  const lastCheck = lastCheckDate ? dayjs(lastCheckDate) : now.subtract(1, 'day');
  const newTransactions = [];

  const recurringTransactions = transactions.filter(t => t.isRecurring && t.recurringInterval);

  recurringTransactions.forEach(recurring => {
    const lastOccurrence = getLastOccurrence(recurring, transactions);
    const nextDue = getNextDueDate(lastOccurrence, recurring.recurringInterval);

    // Generate all missed occurrences between last check and now
    let currentDue = nextDue;
    while (currentDue.isBefore(now) || currentDue.isSame(now, 'day')) {
      // Avoid creating duplicates for today if already created
      const alreadyExists = transactions.some(t =>
        t.parentRecurringId === recurring.id &&
        dayjs(t.date).isSame(currentDue, 'day')
      );

      if (!alreadyExists) {
        newTransactions.push({
          id: generateId(),
          type: recurring.type,
          amount: recurring.amount,
          category: recurring.category,
          description: recurring.description,
          date: currentDue.toISOString(),
          isRecurring: false,
          parentRecurringId: recurring.id,
          autoGenerated: true,
        });
      }

      currentDue = getNextDueDate(currentDue, recurring.recurringInterval);
    }
  });

  return newTransactions;
};

/**
 * Get the last occurrence of a recurring transaction
 */
const getLastOccurrence = (recurring, allTransactions) => {
  const children = allTransactions
    .filter(t => t.parentRecurringId === recurring.id)
    .sort((a, b) => dayjs(b.date).valueOf() - dayjs(a.date).valueOf());

  if (children.length > 0) {
    return dayjs(children[0].date);
  }
  return dayjs(recurring.date);
};

/**
 * Calculate next due date based on interval
 */
const getNextDueDate = (fromDate, interval) => {
  const date = dayjs(fromDate);
  switch (interval) {
    case 'daily':
      return date.add(1, 'day');
    case 'weekly':
      return date.add(1, 'week');
    case 'monthly':
      return date.add(1, 'month');
    case 'yearly':
      return date.add(1, 'year');
    default:
      return date.add(1, 'month');
  }
};

/**
 * Generate a simple unique ID
 */
const generateId = () => {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
};

/**
 * Get human-readable label for interval
 */
export const getIntervalLabel = (interval) => {
  const labels = {
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
  };
  return labels[interval] || 'Monthly';
};

export const RECURRING_INTERVALS = [
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'monthly', label: 'Monthly' },
  { value: 'yearly', label: 'Yearly' },
];

export default {
  processRecurringTransactions,
  getIntervalLabel,
  RECURRING_INTERVALS,
};
